# Generated by Django 3.0 on 2020-01-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('rzjd', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=30)),
                ('zwname', models.CharField(max_length=30)),
                ('gzjy', models.CharField(max_length=20)),
                ('xueli', models.CharField(max_length=30)),
                ('money', models.CharField(max_length=30)),
                ('zwfl', models.CharField(max_length=50)),
                ('jyfanwei', models.CharField(max_length=30)),
                ('zwtype', models.CharField(max_length=50)),
                ('gsfl', models.CharField(max_length=50)),
                ('drzwjy', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('detail_link', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(null=True)),
                ('city_count', models.IntegerField(null=True)),
            ],
        ),
    ]
