# Generated by Django 3.0 on 2020-01-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(default='avatar/default.jpeg', upload_to='avatar/')),
            ],
        ),
    ]
